### PR TITLE
fix(search): close keyboard on enter press

### LINKED ISSUE #1297: [FEATURE] Search on enter key press close keyboard / focus out
close the keyboard on enter key press so it does not obscure search results.

### PR DESCRIPTION
**Pull request by shadow81627**
resolves #1297

### CODE REVIEW

File: scrape/index.js [hunk 1]
```diff
@@ -26,7 +44,7 @@ const fileUrlMap = {};
  * Main top level async/await
  */
 (async () => {
-  const collection = 'recipes';
+  const { collection } = argv;
```
Comment (shadow81627) [inline scrape/index.js:47]: Codacy found an issue: [Unnecessary block.](https://app.codacy.com/manual/damien.robinson/pocketpasta/pullRequest?prid=5802383)

**Comment by shadow81627** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
- Added 1
           

Complexity increasing per file
==============================
- scrape/index.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/damien.robinson/pocketpasta/pullRequest?prid=5802383&bid=18995228)

**Comment by shadow81627** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
           

Complexity increasing per file
==============================
- scrape/index.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/damien.robinson/pocketpasta/pullRequest?prid=5802383&bid=18995228)
